server:
  port: 12345
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: dkssudgktpdy
    key-store-type: PKCS12
    key-alias: bootsecurity

spring:
  application:
    name: weather

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url : jdbc:h2:~/test
      username : root
      password :

mybatis:
  mapper-locations:
    - mappers/*.xml

